import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { fileURLToPath } from 'node:url'

// The demo is served by MkDocs at /demo/ (and on GitHub Pages under a project
// subpath), so assets must be referenced relatively — never from an absolute
// root. `base: './'` makes the bundle self-contained wherever it is mounted.
export default defineConfig({
  base: './',
  plugins: [react()],
  build: {
    // Replace the old single-file explorer. MkDocs picks this up as a static
    // page at docs/demo/index.html (see .github/workflows/deploy.yml).
    outDir: fileURLToPath(new URL('../docs/demo', import.meta.url)),
    emptyOutDir: true,
    chunkSizeWarningLimit: 1400, // the healthspan graph is a ~600KB data import
  },
  server: {
    // Allow importing the compiled healthspan graph from ../prototype (the
    // single source of truth, regenerated by prototype/build.mjs).
    fs: { allow: ['..'] },
  },
})
